### ISSUE TITLE
only 4 threads are used

### ISSUE THREAD

**Issue by badsmoke** [go-skynet/LocalAI#498]
**LocalAI version:**
latest docker image

**Environment, CPU architecture, OS, and Version:**
Ryzen 9 3900X -> 12 Cores 24 Threads
windows 10 -> wsl (5.15.90.1-microsoft-standard-WSL2 ) docker

**Describe the bug**
i have the model ggml-gpt4all-l13b-snoozy.bin
but only a maximum of 4 threads are used.

docker-compose.yml
```
version: "3.9"
services:
  localai:
    image: quay.io/go-skynet/local-ai:latest
    volumes:
      - ./models:/models
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
    command:
       --models-path /models
       --context-size 1024
       --threads 23
       --debug

```

model file
models/gpt-3.5-turbo.yaml 
```
name: gpt-3.5-turbo
# Default model parameters
parameters:
  # Relative to the models path
  model: ggml-gpt4all-l13b-snoozy.bin
  # temperature
  temperature: 0.3
  # all the OpenAI request options here..

# Default context size
context_size: 512
threads: 23
# Define a backend (optional). By default it will try to guess the backend the first time the model is interacted with.
#backend: gptj # available: llama, stablelm, gpt2, gptj rwkv
# stopwords (if supported by the backend)
stopwords:
- "HUMAN:"
- "### Response:"
# define chat roles
roles:
  user: "HUMAN:"
  system: "GPT:"
template:
  # template file ".tmpl" with the prompt template to use by default on the endpoint call. Note there is no extension in the files
  completion: completion
  chat: ggml-gpt4all-l13b-snoozy
```
template
```
The prompt below is a question to answer, a task to complete, or a conversation to respond to; decide which and write an appropriate response.
### Prompt:
{{.Input}}
### Response:
```

e.g. command

```
curl http://localhost:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
     "model": "ggml-gpt4all-l13b-snoozy.bin",
     "messages": [{"role": "user", "content": "What is Kubernetes?"}],
     "temperature": 0.7
   }'
```

thanks
