### ISSUE TITLE
Cublas build broken

### ISSUE THREAD

**Issue by guyguy333** [go-skynet/LocalAI#611]
**LocalAI version:** 

295f3030a9f76f7f36705abb760a2cd351d2b4d8

**Environment, CPU architecture, OS, and Version:** 

Debian 12, AMD64

**Describe the bug**

Build with Cublas is currently broken in two different parts:
- If you use golang:1.20 as base image, as Go image has been updated to Debian 12, GCC is now using 12 so you need CUDA 12.x. If I force CUDA version 12.0 then I get same error as the second one.
- If I force golang:1.20.1, then Docker build is also broken with this error:

```
...
#0 305.4 -- Linux detected
#0 305.4 -- x86 detected
#0 305.4 -- Linux detected
#0 305.5 CMake Error at tests/CMakeLists.txt:145 (set_target_properties):
#0 305.5   set_target_properties called with incorrect number of arguments.
#0 305.5 
#0 305.5 
#0 305.5 -- Configuring incomplete, errors occurred!
#0 305.5 See also "/build/go-ggml-transformers/build/CMakeFiles/CMakeOutput.log".
#0 305.5 See also "/build/go-ggml-transformers/build/CMakeFiles/CMakeError.log".
#0 305.5 make[1]: Leaving directory '/build/go-ggml-transformers'
#0 305.5 make[1]: *** [Makefile:144: ggml.o] Error 1
#0 305.5 make: *** [Makefile:156: go-ggml-transformers/libtransformers.a] Error 2
------
failed to solve: process "/bin/sh -c make prepare" did not complete successfully: exit code: 2
```

**To Reproduce**

- Build Docker image with arg `BUILD_TYPE: cublas`, `CUDA_MAJOR_VERSION: 12`and `CUDA_MINOR_VERSION: 0`
- Build Docker image with arg `BUILD_TYPE: cublas` and FROM image golang:1.20.1

**Expected behavior**

Docker build image works

**Logs**

See above

**Additional context**

**Comment by guyguy333** [comment]
Thanks @mudler for checking my issue. However, second issue is still present. It can be easily reproduced using an image on your repo:

```yaml
version: '3.6'

services:
  api:
    image: quay.io/go-skynet/local-ai:v0.19.0-cublas-cuda11-ffmpeg
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./models:/models:cached
    command: ["/usr/bin/local-ai" ]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
 ```

Just start this docker-compose and it will end with this error:

```
[...]
localai-api-1  | CMake Error at tests/CMakeLists.txt:145 (set_target_properties):
localai-api-1  |   set_target_properties called with incorrect number of arguments.
```

Thanks
