### ISSUE TITLE
Cannot get this to run on Proxmox

### ISSUE THREAD

**Issue by arsaboo** [go-skynet/LocalAI#773]
**LocalAI version:**
1.21.0

**Environment, CPU architecture, OS, and Version:**
Proxmox VM (with CPU set to host)
Linux localai 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Describe the bug**
I am unable to get started. Whether I use rebuild=True or not, I get the following in the logs (I followed the instructions in the Readme to get started):
```
1:54PM DBG no galleries to load
1:54PM INF Starting LocalAI using 4 threads, with models path: /models
1:54PM INF LocalAI version: v1.21.0 (fb6cce487fb53d9de1c1a6b3414261f52b5cdbe0)

 ┌───────────────────────────────────────────────────┐
 │                   Fiber v2.48.0                   │
 │               http://127.0.0.1:8080               │
 │       (bound on host 0.0.0.0 and port 8080)       │
 │                                                   │
 │ Handlers ............ 31  Processes ........... 1 │
 │ Prefork ....... Disabled  PID .............. 7164 │
 └───────────────────────────────────────────────────┘

rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:41937: connect: connection refused"
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:43565: connect: connection refused"
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:35255: connect: connection refused"
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 127.0.0.1:40915: connect: connection refused"
```
When I run `curl http://localhost:8080/v1/models`, I get:
```
{"object":"list","data":[{"id":"ggml-gpt4all-j","object":"model"}]}
```
However, when I run 
```
curl http://192.168.2.110:8080/v1/chat/completions -H "Content-Type: application/json" -d '{
     "model": "ggml-gpt4all-j",
     "messages": [{"role": "user", "content": "How are you?"}],
     "temperature": 0.9
   }'
```

after a long wait, I get:
```bash
{"error":{"code":500,"message":"could not load model - all backends returned error: 12 errors occurred:\n\t* rpc error: code = Unavailable desc = error reading from server: EOF\n\t* rpc error: code = Unavailable desc = error reading from server: EOF\n\t* rpc error: code = Unavailable desc = error reading from server: EOF\n\t* rpc error: code = Unavailable desc = error reading from server: EOF\n\t* rpc error: code = Unavailable desc = error reading from server: EOF\n\t* rpc error: code = Unavailable desc = error reading from server: EOF\n\t* rpc error: code = Unavailable desc = error reading from server: EOF\n\t* rpc error: code = Unknown desc = failed loading model\n\t* rpc error: code = Unavailable desc = error reading from server: EOF\n\t* rpc error: code = Unavailable desc = error reading from server: EOF\n\t* rpc error: code = Unavailable desc = error reading from server: EOF\n\t* rpc error: code = Unknown desc = failed loading model\n\n","type":""}}
```

CPUinfo:
```bash
$ cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 151
model name      : 12th Gen Intel(R) Core(TM) i9-12900T
stepping        : 2
microcode       : 0x1e
cpu MHz         : 1382.400
cache size      : 16384 KB
physical id     : 0
siblings        : 3
core id         : 0
cpu cores       : 3
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 31
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves avx_vnni arat umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_capabilities
vmx flags       : vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid shadow_vmcs pml tsc_scaling
bugs            : spectre_v1 spectre_v2 spec_store_bypass swapgs eibrs_pbrsb
bogomips        : 2764.80
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 151
model name      : 12th Gen Intel(R) Core(TM) i9-12900T
stepping        : 2
microcode       : 0x1e
cpu MHz         : 1382.400
cache size      : 16384 KB
physical id     : 0
siblings        : 3
core id         : 1
cpu cores       : 3
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 31
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves avx_vnni arat umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_capabilities
vmx flags       : vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid shadow_vmcs pml tsc_scaling
bugs            : spectre_v1 spectre_v2 spec_store_bypass swapgs eibrs_pbrsb
bogomips        : 2764.80
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 151
model name      : 12th Gen Intel(R) Core(TM) i9-12900T
stepping        : 2
microcode       : 0x1e
cpu MHz         : 1382.400
cache size      : 16384 KB
physical id     : 0
siblings        : 3
core id         : 2
cpu cores       : 3
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 31
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves avx_vnni arat umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_capabilities
vmx flags       : vnmi preemption_timer posted_intr invvpid ept_x_only ept_ad ept_1gb flexpriority apicv tsc_offset vtpr mtf vapic ept vpid unrestricted_guest vapic_reg vid shadow_vmcs pml tsc_scaling
bugs            : spectre_v1 spectre_v2 spec_store_bypass swapgs eibrs_pbrsb
bogomips        : 2764.80
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```
Let me know if I can provide any additional information.

**Comment by simonbermudez** [comment]
I have the same issue running on an HP Z800 running Ubuntu 22.04

**Comment by emakkus** [comment]
This: "model": "ggml-gpt4all-j"
is propably a ggml-gpt4all-j.yaml right?

You can look into the /models path where the models should reside. There should be a yaml file with the same name. If you instead just have the *.bin file there, localai will throw the model at all possible backends until something sticks. I had problem with that though, since the ram filled up and everything went to a crawl. My solution was to create the *.yaml that points to the *.bin file and tells localai which backend to use.

Here is my guanaco.yaml example, that is in the /model directory together witht he model itself:

`name: guanaco
backend: llama
context_size: 4096
parameters:
  model: guanaco-33B.ggmlv3.q4_0.bin
  temperature: 0.2
  top_k: 80
  top_p: 0.7
  
gpu_layers: 60
roles:
  assistant: 'Assistant:'
  system: 'System:'
  user: 'User:'
template:
  chat: guanaco-chat
  completion: guanaco-completion`

**Comment by arsaboo** [comment]
Ok...so I created the yaml file:
```yaml
name: "gpt4all-j"
description: |
    A commercially licensable model based on GPT-J and trained by Nomic AI on the v0 GPT4All dataset.
license: "Apache 2.0"
urls:
- https://gpt4all.io
config_file: |
    backend: gpt4all-j
    parameters:
      model: ggml-gpt4all-j.bin
      top_k: 80
      temperature: 0.2
      top_p: 0.7
    context_size: 1024
    template:
      completion: "gpt4all-completion"
      chat: gpt4all-chat

files:
    - filename: "ggml-gpt4all-j.bin"
      sha256: "acd54f6da1cad7c04c48b785178d686c720dcbe549903032a0945f97b1a43d20"
      uri: "https://gpt4all.io/models/ggml-gpt4all-j.bin"

prompt_templates:
- name: "gpt4all-completion"
  content: |
    Complete the prompt
    ### Prompt:
    {{.Input}}
    ### Response:
- name: "gpt4all-chat"
  content: |
    The prompt below is a question to answer, a task to complete, or a conversation to respond to; decide which and write an appropriate response.
    ### Prompt:
    {{.Input}}
    ### Response:
```

I applied the same using:
```bash
$ curl --location 'http://192.168.2.110:8080/models/apply' --header 'Content-Type: application/json' --data '{
    "url": "file:///models/ggml-gpt4all-j.yaml"
}'
{"uuid":"765102a9-2737-11ee-ae41-0242ac120002","status":"http://192.168.2.110:8080/models/jobs/765102a9-2737-11ee-ae41-0242ac120002"}arsaboo@localai:~/LocalAI/models
```

However, even after this I get the same error:
```bash
$ curl http://192.168.2.110:8080/v1/chat/completions -H "Content-Type: application/json" -d '{"model": "ggml-gpt4all-j", "messages": [{"role": "user", "content": "How are you?"}], "temperature": 0.9}'
{"error":{"code":500,"message":"could not load model - all backends returned error: 12 errors occurred:\n\t* rpc error: code = Unknown desc = failed loading model\n\t* rpc error: code = Unknown desc = failed loading model\n\t* rpc error: code = Unknown desc = failed loading model\n\t* rpc error: code = Unknown desc = failed loading model\n\t* rpc error: code = Unknown desc = failed loading model\n\t* rpc error: code = Unknown desc = failed loading model\n\t* rpc error: code = Unknown desc = failed loading model\n\t* rpc error: code = Unknown desc = failed loading model\n\t* rpc error: code = Unknown desc = failed loading model\n\t* rpc error: code = Unknown desc = failed loading model\n\t* rpc error: code = Unknown desc = failed loading model\n\t* rpc error: code = Unknown desc = failed loading model\n\n","type":""}}arsaboo@localai:~/LocalAI/models
```

**Comment by arsaboo** [comment]
Even when I use the following yaml file, I get the same error:
```yaml

backend: ggml-gpt4all-j
context_size: 1024
parameters:
  model: ggml-gpt4all-j.bin
  temperature: 0.2
  top_k: 80
  top_p: 0.7

gpu_layers: 60
roles:
  assistant: 'Assistant:'
  system: 'System:'
  user: 'User:'
template:
  chat: gpt4-chat
  completion: gpt4-completion
```
